# Generated by Django 6.0.3 on 2026-03-22 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0002_campus_course_semester_alter_academicprogram_code_and_more'),
        ('access_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('jornada', models.CharField(blank=True, max_length=20, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.campus')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.faculty')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.academicprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
