# Generated by Django 6.0.3 on 2026-04-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_support', '0002_alter_studentprofile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='document_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
