# Generated by Django 6.0.3 on 2026-03-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_support', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
