# Generated by Django 6.0.4 on 2026-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_support', '0003_alter_studentprofile_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Docente'), ('admin', 'Administrador'), ('coordinator', 'Director academico')], default='student', max_length=20),
        ),
    ]
