# Generated by Django 5.2.5 on 2026-03-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0003_alter_coursegroup_term'),
        ('classrooms', '0002_alter_timeslot_options_classroom_capacity_and_more'),
        ('scheduling_enrollment', '0001_initial'),
        ('teaching', '0002_contractrule_remove_teacher_type_of_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='nrc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.academicterm'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='capacity',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.teacher'),
        ),
        migrations.CreateModel(
            name='ProposedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=20)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_schedules', to='teaching.teacher')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroom')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling_enrollment.coursegroup')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling_enrollment.proposedschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
