# Generated by Django 5.2.5 on 2026-03-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0003_alter_coursegroup_term'),
        ('scheduling_enrollment', '0002_remove_coursegroup_classroom_and_more'),
        ('teaching', '0002_contractrule_remove_teacher_type_of_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'Grupo de horario', 'verbose_name_plural': 'Grupos de horario'},
        ),
        migrations.AddField(
            model_name='proposedschedule',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TeacherActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('asesoria', 'Asesoría'), ('investigacion', 'Investigación')], max_length=20)),
                ('day', models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teaching.teacher')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.academicterm')),
            ],
            options={
                'verbose_name': 'Actividad docente',
                'verbose_name_plural': 'Actividades docentes',
            },
        ),
    ]
