# Generated by Codex on 2026-04-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_core", "0004_alter_academicprogram_id_alter_academicterm_id_and_more"),
        ("classrooms", "0003_alter_classroom_id_alter_timeslot_id"),
        ("teaching", "0003_alter_availability_id_alter_contractrule_id_and_more"),
        (
            "scheduling_enrollment",
            "0004_alter_coursegroup_id_alter_enrollmentqueue_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmentqueue",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment_requests",
                to="academic_core.academicterm",
            ),
        ),
        migrations.CreateModel(
            name="SemesterScheduleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("applied", "Aplicado")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_schedule_runs",
                        to="academic_core.academicterm",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SemesterScheduleOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("score", models.FloatField(default=0.0)),
                ("demand_covered", models.PositiveIntegerField(default=0)),
                ("demand_total", models.PositiveIntegerField(default=0)),
                ("sections_opened", models.PositiveIntegerField(default=0)),
                ("is_best", models.BooleanField(default=False)),
                ("applied", models.BooleanField(default=False)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="scheduling_enrollment.semesterschedulerun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-score"],
                "unique_together": {("run", "rank")},
            },
        ),
        migrations.CreateModel(
            name="SemesterScheduleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_number", models.PositiveSmallIntegerField(default=1)),
                ("nrc", models.CharField(blank=True, max_length=20)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Lunes"),
                            ("Tuesday", "Martes"),
                            ("Wednesday", "Miercoles"),
                            ("Thursday", "Jueves"),
                            ("Friday", "Viernes"),
                            ("Saturday", "Sabado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("students_assigned", models.PositiveSmallIntegerField(default=0)),
                ("capacity", models.PositiveSmallIntegerField(default=20)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic_core.course",
                    ),
                ),
                (
                    "generated_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="semester_assignments",
                        to="scheduling_enrollment.coursegroup",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling_enrollment.semesterscheduleoption",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teaching.teacher",
                    ),
                ),
            ],
            options={"ordering": ["course__code", "section_number"]},
        ),
    ]
