# Generated by Django 6.0.4 on 2026-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_enrollment', '0010_enrollment_and_run_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterscheduleassignment',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado')], max_length=10),
        ),
    ]
