# Generated by Django 6.0.6 on 2026-07-01 14:49

from datetime import datetime, timedelta

from django.conf import settings
from django.db import migrations, models


def normalize_time_range(instance):
    if instance.end_time > instance.start_time:
        return False
    start = datetime.combine(datetime.today(), instance.start_time)
    instance.end_time = (start + timedelta(minutes=1)).time()
    if instance.end_time <= instance.start_time:
        instance.start_time = (start - timedelta(minutes=1)).time()
        instance.end_time = start.time()
    return True


def normalize_scheduling_data(apps, schema_editor):
    CourseGroup = apps.get_model("scheduling_enrollment", "CourseGroup")
    EnrollmentQueue = apps.get_model(
        "scheduling_enrollment", "EnrollmentQueue"
    )
    Enrollment = apps.get_model("scheduling_enrollment", "Enrollment")
    ScheduleSession = apps.get_model(
        "scheduling_enrollment", "ScheduleSession"
    )
    Assignment = apps.get_model(
        "scheduling_enrollment", "SemesterScheduleAssignment"
    )
    Option = apps.get_model(
        "scheduling_enrollment", "SemesterScheduleOption"
    )
    TeacherActivity = apps.get_model(
        "scheduling_enrollment", "TeacherActivity"
    )

    used_nrcs = set()
    for group in CourseGroup.objects.order_by("id"):
        if group.capacity <= 0:
            group.capacity = 40
        if group.nrc:
            key = (group.term_id, group.nrc)
            if key in used_nrcs:
                candidate_number = group.id
                while key in used_nrcs:
                    suffix = str(candidate_number)
                    group.nrc = (
                        f"{group.nrc[:10 - len(suffix)]}{suffix}"[-10:]
                    )
                    key = (group.term_id, group.nrc)
                    candidate_number += 1
            used_nrcs.add(key)
        group.save(update_fields=["capacity", "nrc"])

    request_keys = {}
    for request in EnrollmentQueue.objects.order_by("id"):
        key = (request.student_id, request.course_id, request.term_id)
        keeper = request_keys.get(key)
        if keeper is None:
            request_keys[key] = request
            continue
        linked_enrollment = Enrollment.objects.filter(request_id=request.id).first()
        if linked_enrollment:
            if not Enrollment.objects.filter(request_id=keeper.id).exists():
                linked_enrollment.request_id = keeper.id
                linked_enrollment.save(update_fields=["request"])
            else:
                linked_enrollment.request_id = None
                linked_enrollment.save(update_fields=["request"])
        if request.status == "enrolled":
            keeper.status = "enrolled"
            keeper.course_group_id = request.course_group_id
            keeper.save(update_fields=["status", "course_group"])
        request.delete()

    session_keys = set()
    for session in ScheduleSession.objects.order_by("id"):
        time_changed = normalize_time_range(session)
        key = (
            session.schedule_id,
            session.group_id,
            session.day,
            session.start_time,
            session.end_time,
        )
        if key in session_keys:
            session.delete()
        else:
            session_keys.add(key)
            if time_changed:
                session.save(update_fields=["start_time", "end_time"])

    for assignment in Assignment.objects.all():
        changed = []
        if normalize_time_range(assignment):
            changed.extend(["start_time", "end_time"])
        if assignment.capacity <= 0:
            assignment.capacity = max(assignment.students_assigned, 1)
            changed.append("capacity")
        if assignment.students_assigned < 0:
            assignment.students_assigned = 0
            changed.append("students_assigned")
        if assignment.students_assigned > assignment.capacity:
            assignment.capacity = assignment.students_assigned
            changed.append("capacity")
        if changed:
            assignment.save(update_fields=list(set(changed)))

    for run_id in Option.objects.values_list("run_id", flat=True).distinct():
        selected = list(
            Option.objects.filter(run_id=run_id, selected=True).order_by(
                "rank", "id"
            )
        )
        if len(selected) > 1:
            Option.objects.filter(
                id__in=[option.id for option in selected[1:]]
            ).update(selected=False)
        applied = list(
            Option.objects.filter(run_id=run_id, applied=True).order_by(
                "rank", "id"
            )
        )
        if len(applied) > 1:
            Option.objects.filter(
                id__in=[option.id for option in applied[1:]]
            ).update(applied=False)

    activity_keys = set()
    for activity in TeacherActivity.objects.order_by("id"):
        time_changed = normalize_time_range(activity)
        key = (
            activity.teacher_id,
            activity.term_id,
            activity.activity_type,
            activity.day,
            activity.start_time,
            activity.end_time,
        )
        if key in activity_keys:
            activity.delete()
        else:
            activity_keys.add(key)
            if time_changed:
                activity.save(update_fields=["start_time", "end_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0006_curriculumcoursegroup_remove_coursegroup_course_and_more'),
        ('classrooms', '0005_timeslot_timeslot_end_after_start'),
        ('scheduling_enrollment', '0012_alter_coursegroup_id_alter_enrollment_id_and_more'),
        ('teaching', '0006_availability_availability_end_after_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            normalize_scheduling_data,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.UniqueConstraint(condition=models.Q(('nrc', ''), _negated=True), fields=('term', 'nrc'), name='unique_nrc_per_term'),
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='schedule_group_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentqueue',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'term'), name='unique_enrollment_request_per_term'),
        ),
        migrations.AddConstraint(
            model_name='schedulesession',
            constraint=models.UniqueConstraint(fields=('schedule', 'group', 'day', 'start_time', 'end_time'), name='unique_schedule_session'),
        ),
        migrations.AddConstraint(
            model_name='schedulesession',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='semesterscheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='assignment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='semesterscheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='assignment_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='semesterscheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('students_assigned__gte', 0), ('students_assigned__lte', models.F('capacity'))), name='assignment_students_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='semesterscheduleoption',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('run',), name='one_selected_option_per_run'),
        ),
        migrations.AddConstraint(
            model_name='semesterscheduleoption',
            constraint=models.UniqueConstraint(condition=models.Q(('applied', True)), fields=('run',), name='one_applied_option_per_run'),
        ),
        migrations.AddConstraint(
            model_name='teacheractivity',
            constraint=models.UniqueConstraint(fields=('teacher', 'term', 'activity_type', 'day', 'start_time', 'end_time'), name='unique_teacher_activity_slot'),
        ),
        migrations.AddConstraint(
            model_name='teacheractivity',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='teacher_activity_end_after_start'),
        ),
    ]
