# Generated by Django 6.0.6 on 2026-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_enrollment', '0013_coursegroup_unique_nrc_per_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterschedulerun',
            name='random_seed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
