# Generated by Django 6.0.3 on 2026-03-22 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0002_campus_course_semester_alter_academicprogram_code_and_more'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.campus'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
