# Generated by Django 5.2.5 on 2026-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('SALON', 'Salón'), ('SISTEMAS', 'Aula de Sistemas'), ('LAB', 'Laboratorio'), ('AUDITORIO', 'Auditorio'), ('VIRTUAL', 'Virtual')], default='SALON', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'start_time', 'end_time')},
        ),
    ]
