# Generated by Django 6.0.3 on 2026-03-22 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_campus_classroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.AddField(
            model_name='classroom',
            name='block',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='bloque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
