# Generated by Django 6.0.6 on 2026-07-01 14:49

from datetime import datetime, timedelta

from django.db import migrations, models


def normalize_timeslots(apps, schema_editor):
    TimeSlot = apps.get_model("classrooms", "TimeSlot")
    for slot in TimeSlot.objects.all():
        if slot.end_time <= slot.start_time:
            start = datetime.combine(datetime.today(), slot.start_time)
            slot.end_time = (start + timedelta(minutes=1)).time()
            if slot.end_time <= slot.start_time:
                slot.start_time = (start - timedelta(minutes=1)).time()
                slot.end_time = start.time()
            slot.save(update_fields=["start_time", "end_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_alter_classroom_id_alter_timeslot_id'),
    ]

    operations = [
        migrations.RunPython(normalize_timeslots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timeslot_end_after_start'),
        ),
    ]
