# Generated by Django 5.2.5 on 2026-03-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0003_alter_coursegroup_term'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=20, unique=True)),
                ('min_teaching_hours', models.PositiveSmallIntegerField()),
                ('max_teaching_hours', models.PositiveSmallIntegerField()),
                ('max_advisory_hours', models.PositiveSmallIntegerField(default=0)),
                ('max_research_hours', models.PositiveSmallIntegerField(default=0)),
                ('max_total_hours', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='type_of_contract',
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualified_courses',
            field=models.ManyToManyField(blank=True, related_name='qualified_teachers', to='academic_core.course'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.contractrule'),
        ),
    ]
