# Generated by Django 6.0.3 on 2026-04-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_contractrule_remove_teacher_type_of_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
