# Generated by Django 6.0.6 on 2026-07-01 14:49

from datetime import datetime, timedelta

from django.db import migrations, models


def normalize_availability(apps, schema_editor):
    Availability = apps.get_model("teaching", "Availability")
    for availability in Availability.objects.all():
        if availability.end_time <= availability.start_time:
            start = datetime.combine(datetime.today(), availability.start_time)
            availability.end_time = (start + timedelta(minutes=1)).time()
            if availability.end_time <= availability.start_time:
                availability.start_time = (start - timedelta(minutes=1)).time()
                availability.end_time = start.time()
            availability.save(update_fields=["start_time", "end_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_alter_availability_id_alter_contractrule_id_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_availability, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
    ]
