# Generated by Django 5.2.5 on 2026-03-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0002_seed_study_plans_and_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_course_groups', to='academic_core.academicterm'),
        ),
    ]
